# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/usuario_local/Downloads/Practica4_1/project_4/project_4.srcs/sources_1/bd/design_4/ip/design_4_dlmb_v10_0/design_4_dlmb_v10_0.xci
# IP: The module: 'design_4_dlmb_v10_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/usuario_local/Downloads/Practica4_1/project_4/project_4.gen/sources_1/bd/design_4/ip/design_4_dlmb_v10_0/design_4_dlmb_v10_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_4_dlmb_v10_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/Users/usuario_local/Downloads/Practica4_1/project_4/project_4.srcs/sources_1/bd/design_4/ip/design_4_dlmb_v10_0/design_4_dlmb_v10_0.xci
# IP: The module: 'design_4_dlmb_v10_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/usuario_local/Downloads/Practica4_1/project_4/project_4.gen/sources_1/bd/design_4/ip/design_4_dlmb_v10_0/design_4_dlmb_v10_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_4_dlmb_v10_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
